# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches-ignore:
      - 'qa'
      - 'stage'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: sh ci-cd/install-dependencies.sh
      env:
        ARTIFACTORY_READER_PASSWORD: ${{ secrets.ARTIFACTORY_READER_PASSWORD }}
        ARTIFACTORY_READER_USER: ${{ secrets.ARTIFACTORY_READER_USER }}
    - run: npm run build
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: sh ci-cd/install-dependencies.sh
      env:
        ARTIFACTORY_READER_PASSWORD: ${{ secrets.ARTIFACTORY_READER_PASSWORD }}
        ARTIFACTORY_READER_USER: ${{ secrets.ARTIFACTORY_READER_USER }}
    - run: npm run test
  sonar:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Restore cache
      uses: actions/cache@v2
      id: cache-app
      env:
        cache-name: angular-source
      with:
        path: src
        key: ${{ env.cache-name }}-${{ hashFiles('**/src/**','**/*.properties') }}-cache
    - name: Get coverage file
      uses: actions/download-artifact@v1
      with:
        name: coverage
   
    - name: Checkout bancodebogota/bbog-dig-sonarcloud-pipeline
      uses: actions/checkout@v2
      with:
        repository: bancodebogota/bbog-dig-sonarcloud-pipeline
        ref: 0.1.0
        token: ${{secrets.DIG_READER_GITHUB_ACCESS_TOKEN}}
        persist-credentials: false
        path: ./.github/actions/bbog-dig-sonarcloud-pipeline
 
    - name: set-long-branch-name
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
        CURRENT_BRANCH="$BRANCH_NAME"
        if [ "$CURRENT_BRANCH" != "master" ] && [ "$CURRENT_BRANCH" != "staging" ] && [ "$CURRENT_BRANCH" != "qa" ]
        then
          CURRENT_BRANCH="qa"
        fi
        echo "Sonar Branch report => " ${CURRENT_BRANCH}
        echo "CURRENT_BRANCH='${CURRENT_BRANCH}'" >> $GITHUB_ENV
    - name: Report to sonar
      uses: ./.github/actions/bbog-dig-sonarcloud-pipeline
      with:
        access-token: ${{ secrets.SONAR_CLOUD_TOKEN }}
        project-name: ${{ github.event.repository.name }}
        project-key: ${{ github.event.repository.name }}
        organization: ${{ secrets.SONAR_CLOUD_ORG }}
        current-branch: ${{env.CURRENT_BRANCH}}
        language: 'javascript'
        debug: 'true'
      if: steps.cache-app.outputs.cache-hit != 'true'
